version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - OlegRa
  assignees:
  - OlegRa
  ignore:
  - dependency-name: Alpaca.Markets
    versions:
    - "> 3.9.0, < 3.10"
  - dependency-name: Alpaca.Markets.Extensions
    versions:
    - 5.0.1-alpha3
  - dependency-name: Alpaca.Markets
    versions:
    - 5.0.0-alpha6
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - OlegRa
  assignees:
  - OlegRa
  ignore:
  - dependency-name: Alpaca.Markets
    versions:
    - 4.1.0
