name: Code Coverage

on: [workflow_dispatch]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Tests
      uses: actions/checkout@v2
      with:
        path: Alpaca.Markets.Tests

    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        repository: alpacahq/alpaca-trade-api-csharp
        path: Alpaca.Markets

    - name: Remove NuGet Lock File
      uses: JesseTG/rm@v1.0.2
      with:
        path: ./Alpaca.Markets/Alpaca.Markets.Extensions/packages.lock.json

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore .NET Tools
      run: dotnet tool restore
      working-directory: ./Alpaca.Markets.Tests

    - name: Coverage All Tests
      env:
        PAPER_ALPACA_KEY_ID: ${{ secrets.PAPER_ALPACA_KEY_ID }}
        PAPER_ALPACA_SECRET_KEY: ${{ secrets.PAPER_ALPACA_SECRET_KEY }}
      run: dotnet dotcover test --dcXML=../Configuration.xml --force-evaluate
      working-directory: ./Alpaca.Markets.Tests/Alpaca.Markets.Coverage

    - name: Save Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: Alpaca.Markets.Coverage.xml
