name: Code Coverage

on: [workflow_dispatch]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Tests
      uses: actions/checkout@v2

    - name: Checkout Sources
      uses: actions/checkout@v2
      with:
        repository: alpacahq/alpaca-trade-api-csharp
        path: Alpaca.Markets

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Cache NuGet Packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Run All Tests
      env:
        PAPER_ALPACA_KEY_ID: ${{ secrets.PAPER_ALPACA_KEY_ID }}
        PAPER_ALPACA_SECRET_KEY: ${{ secrets.PAPER_ALPACA_SECRET_KEY }}
      run: dotnet dotcover test --dcXML=Configuration.xml Alpaca.Markets.Coverage\Alpaca.Markets.Coverage.sln

    - name: Save Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: Alpaca.Markets.Coverage.xml
